name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Docker build 
        run: docker build ./django/ -t ${{ secrets.DOCKER_HUB_USERNAME }}/probeaufgabe-django:latest
      - name: push image django 
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB}}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/probeaufgabe-django:latest
      - name: clone nodjs ripo 
        run: |
          cd nodejs
          git clone https://github.com/microsoft/project-nodejs-express-webapp.git
      - name: docker build nodjs
        run: docker build . -t  ${{ secrets.DOCKER_HUB_USERNAME }}/probeaufgabe-nodejs:latest
        
      - name: push image nodejs
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB}}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/probeaufgabe-nodejs:latest
        
        
